create-html-index: add a force option
Signed-off-by: John Else <john.else@gmail.com>

diff --git a/scripts/create-html-index b/scripts/create-html-index
--- a/scripts/create-html-index
+++ b/scripts/create-html-index
@@ -4,9 +4,23 @@
 
 IFS=$(echo -en "\n\b")
 
-if [ -a index.html ]
+FORCE=false
+
+while getopts ":f" opt
+do
+    case $opt in
+        f)
+            FORCE=true
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            ;;
+    esac
+done
+
+if [ -a index.html -a $FORCE == false ]
 then
-    echo "index.html already exists"
+    echo "index.html already exists - use -f to force"
     exit 1
 fi
 
